version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: userservice-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - socialsynchub-network

  userservice:
    build:
      context: ./services/UserService/UserService.API
      dockerfile: Dockerfile
    container_name: userservice-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=UserServiceDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - socialsynchub-network

  gateway:
    build:
      context: ./gateway/Gateway.API
      dockerfile: Dockerfile
    container_name: socialsynchub-gateway
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - userservice
    networks:
      - socialsynchub-network

volumes:
  sqlserver_data:

networks:
  socialsynchub-network:
    driver: bridge 